import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import PrivacyPolicy from '../PrivacyPolicy';

vi.mock('../../hooks/useSEO', () => ({
  default: vi.fn(),
}));

describe('Privacy policy page', () => {
  it('publishes the verified policy content without unsupported assurances', () => {
    const { container } = render(<PrivacyPolicy />);

    expect(screen.getByRole('heading', { level: 1, name: 'Privacy Policy' })).toBeInTheDocument();
    expect(screen.getByText('Last updated: 10 August 2026')).toBeInTheDocument();
    expect(
      screen.getByText(
        'This policy explains how Dashapatmaja Solutions Pvt Ltd handles information submitted through this website and information generated by website analytics.',
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        'The Contact form collects your name, email address, service requirement, and message. The project planner may also collect your phone or WhatsApp number, company or brand name, website or social handle, services of interest, project details, referral source, preferred contact method, and an optional attachment.',
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        'We use enquiry information to review your request, contact you using the details you provide, prepare or discuss a relevant scope of work, and maintain a record of the enquiry. Project-planner submissions may receive an internal priority label based on the company details and project text submitted. This label is used to organise follow-up; it does not determine eligibility for a service or affect legal rights.',
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        'Contact and project-planner submissions are transmitted through Web3Forms. In production, Google Analytics records page views and selected website interaction events. These providers handle information under their own terms and privacy practices.',
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        'For questions about this policy or information submitted through the website, contact Dashapatmaja Solutions Pvt Ltd at director@dashapatmaja.in or the telephone number listed below.',
      ),
    ).toBeInTheDocument();

    expect(container).not.toHaveTextContent(
      /Terms of Use|newsletter|anonymized|never sell|industry-standard|ephemeral|permanently stored|retained only/i,
    );
  });

  it('keeps the verified headquarters and privacy contact details', () => {
    render(<PrivacyPolicy />);

    expect(screen.getByText('Room No. 12, 4th Floor, MUTBI, Advanced Research Center, Madhava Nagar, Manipal, Karnataka 576104')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'director@dashapatmaja.in' }))
      .toHaveAttribute('href', 'mailto:director@dashapatmaja.in');
    expect(screen.getByRole('link', { name: '+91 88619 42440' }))
      .toHaveAttribute('href', 'tel:+918861942440');
  });
});
