import './PrivacyPolicy.css';
import useSEO from '../hooks/useSEO';
import { getRouteMetadata } from '../seo/routeMetadata';
import PhoneObfuscated from '../components/PhoneObfuscated';


const PrivacyPolicy = () => {
  useSEO(getRouteMetadata('/privacy'));

  return (
    <div className="privacy-page-container">
      <div className="privacy-content glass">
        <h1 className="privacy-title">Privacy Policy</h1>
        <p className="privacy-updated">Last updated: 10 August 2026</p>

        <section className="privacy-section">
          <h2>1. About this policy</h2>
          <p>
            This policy explains how Dashapatmaja Solutions Pvt Ltd handles information submitted through this website and information generated by website analytics.
          </p>
        </section>

        <section className="privacy-section">
          <h2>2. Information handled through the website</h2>
          <p>
            The Contact form collects your name, email address, service requirement, and message. The project planner may also collect your phone or WhatsApp number, company or brand name, website or social handle, services of interest, project details, referral source, preferred contact method, and an optional attachment.
          </p>
        </section>

        <section className="privacy-section">
          <h2>3. How the information is used</h2>
          <p>
            We use enquiry information to review your request, contact you using the details you provide, prepare or discuss a relevant scope of work, and maintain a record of the enquiry. Project-planner submissions may receive an internal priority label based on the company details and project text submitted. This label is used to organise follow-up; it does not determine eligibility for a service or affect legal rights.
          </p>
        </section>

        <section className="privacy-section">
          <h2>4. Service providers and analytics</h2>
          <p>
            Contact and project-planner submissions are transmitted through Web3Forms. In production, Google Analytics records page views and selected website interaction events. These providers handle information under their own terms and privacy practices.
          </p>
        </section>

        <section className="privacy-section">
          <h2>5. Questions about your information</h2>
          <p>
            For questions about this policy or information submitted through the website, contact Dashapatmaja Solutions Pvt Ltd at director@dashapatmaja.in or the telephone number listed below.
          </p>
          <div className="contact-info-card">
            <p><strong>Dashapatmaja Solutions Pvt Ltd</strong></p>
            <p>Room No. 12, 4th Floor, MUTBI, Advanced Research Center, Madhava Nagar, Manipal, Karnataka 576104</p>
            <p>Email: <a href="mailto:director@dashapatmaja.in">director@dashapatmaja.in</a> | Phone: <PhoneObfuscated digits="+918861942440" display="+91 88619 42440" /></p>
          </div>
        </section>
      </div>

    </div>
  );
};

export default PrivacyPolicy;
