import { useState } from 'react';
import './PrivacyPolicy.css';
import useSEO from '../hooks/useSEO';
import { getRouteMetadata } from '../seo/routeMetadata';
import PhoneObfuscated from '../components/PhoneObfuscated';
import { getAnalyticsConsent, setAnalyticsConsent } from '../utils/analytics';
import { COMPANY_FACTS } from '../content/companyFacts';

const PrivacyPolicy = () => {
  useSEO(getRouteMetadata('/privacy'));
  const [analyticsChoice, setAnalyticsChoice] = useState(getAnalyticsConsent);

  const updateAnalyticsChoice = (value) => {
    setAnalyticsConsent(value);
    setAnalyticsChoice(value);
  };

  return (
    <div className="privacy-page-container">
      <article className="privacy-content glass">
        <h1 className="privacy-title">Privacy Policy</h1>
        <p className="privacy-updated">Last updated: 19 August 2026</p>

        <section className="privacy-section">
          <h2>1. Scope and legal context</h2>
          <p>
            This notice explains how {COMPANY_FACTS.legalName} ({COMPANY_FACTS.shortName})
            handles information submitted through this website and information
            generated by optional website analytics. {COMPANY_FACTS.shortName} will assess and handle
            requests in line with obligations applicable to it under the Digital
            Personal Data Protection Act, 2023 as applicable provisions take effect.
          </p>
        </section>

        <section className="privacy-section">
          <h2>2. Information you choose to provide</h2>
          <p>
            The Contact form asks for your first name, email address, the type of
            help required, and a message. You may also provide a last name, phone
            number, company or brand name, website or social handle, and an
            indicative budget.
          </p>
          <p>
            The project planner asks for contact details and services of interest.
            You may also provide company or brand information, a website or social
            handle, project goals, referral source, contact preference, and an
            optional brief or image attachment.
          </p>
        </section>

        <section className="privacy-section">
          <h2>3. Why DSPL uses enquiry information and data retention</h2>
          <p>
            {COMPANY_FACTS.shortName} uses this information to review your enquiry, reply using the
            details you provide, discuss a possible scope of work, and maintain
            operational records needed to manage the enquiry. Submitting a form
            does not automatically create a client relationship.
          </p>
          <p>
            {COMPANY_FACTS.shortName} retains enquiry details and submitted materials only for the
            duration reasonably necessary to review the request, respond to you, evaluate potential
            collaboration, and maintain operational and business records relating to the communication,
            or as required by applicable statutory obligations. Records are periodically reviewed
            and securely deleted or anonymized when no longer required.
          </p>
        </section>

        <section className="privacy-section">
          <h2>4. Form processing through Web3Forms</h2>
          <p>
            Contact and project-planner submissions are transmitted to Web3Forms
            for processing and forwarding to {COMPANY_FACTS.shortName}. Web3Forms states that its
            servers are in the United States US-East Region, that it does not
            store form submissions, and that server logs which may contain
            personally identifiable information are deleted periodically. These
            are Web3Forms' statements, not a {COMPANY_FACTS.shortName} storage-location guarantee.
          </p>
          <p>
            Read the{' '}
            <a href="https://docs.web3forms.com/getting-started/faq" target="_blank" rel="noreferrer">
              Web3Forms privacy documentation
            </a>.
          </p>
        </section>

        <section className="privacy-section">
          <h2>5. Optional Google Analytics</h2>
          <p>
            Google Analytics remains off unless you select Allow analytics. If
            allowed, it may use cookies and identifiers to distinguish visits and
            report page views and selected website interactions. {COMPANY_FACTS.shortName} does not
            send form-field contents as analytics events.
          </p>
          <p>
            You can change your choice below. Google also provides a{' '}
            <a href="https://support.google.com/analytics/answer/181881" target="_blank" rel="noreferrer">
              Google Analytics opt-out browser add-on
            </a>.
          </p>
          <div className="privacy-consent-controls" aria-label="Analytics consent controls">
            <p aria-live="polite">
              Current choice: <strong>{analyticsChoice || 'not selected'}</strong>
            </p>
            <div>
              <button type="button" className="btn btn-primary" onClick={() => updateAnalyticsChoice('granted')}>
                Allow analytics
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => updateAnalyticsChoice('denied')}>
                Decline analytics
              </button>
            </div>
          </div>
        </section>

        <section className="privacy-section">
          <h2>6. Requests and questions</h2>
          <p>
            To ask about information submitted through this website, or to request
            access, correction, or erasure where applicable, email{' '}
            <a href={`mailto:${COMPANY_FACTS.contacts.directorEmail}`}>{COMPANY_FACTS.contacts.directorEmail}</a>.
            {COMPANY_FACTS.shortName} will review the request against the information it holds and the
            obligations that apply at that time.
          </p>
          <div className="contact-info-card">
            <p><strong>{COMPANY_FACTS.legalName}</strong></p>
            <p>{COMPANY_FACTS.registeredOffice.fullAddress}</p>
            <p>Phone: <PhoneObfuscated digits={COMPANY_FACTS.contacts.primaryPhoneDigits} display={COMPANY_FACTS.contacts.primaryPhone} /></p>
          </div>
        </section>
      </article>
    </div>
  );
};

export default PrivacyPolicy;
