/**
 * Publication Model & Article Data Layer for DSPL Insights.
 * Synchronously reads the deterministic snapshot generated by scripts/sync-blog-content.mjs
 * and provides lazy module loading for individual article bodies.
 */

import fallbackManifest from '../generated/blogManifest.json' with { type: 'json' };

/**
 * @typedef {Object} TestimonialRecord
 * @property {string} quote
 * @property {string} name
 * @property {string} role
 * @property {string} company
 * @property {string} consentReference
 */

/**
 * @typedef {Object} PackagingRecord
 * @property {string} image
 * @property {string} [backImage]
 * @property {string} sku
 * @property {string} collection
 * @property {string} description
 * @property {string} category
 * @property {string} alt
 */

/**
 * @typedef {Object} BlogPostSummary
 * @property {string} _id
 * @property {string} _createdAt
 * @property {string} _updatedAt
 * @property {string} slug
 * @property {string} title
 * @property {string} category
 * @property {string} publishedAt
 * @property {string} description
 * @property {{ minutes: number, text: string, wordCount: number }} readingTime
 * @property {Array<{ blockKey: string, id: string, text: string, level: number }>} headings
 * @property {Array<{ _key?: string, name: string, role?: string|null }>|null} [authors]
 * @property {object|null} [mainImage]
 * @property {object|null} [seo]
 */

/**
 * @typedef {BlogPostSummary & {
 *   body: Array<object>,
 *   faqs?: Array<{ _key?: string, question: string, answer: string }>,
 *   references?: Array<{ _key?: string, text: string, url?: string }>,
 *   closingCta?: { heading: string, text: string, label: string, href: string },
 * }} BlogPostFull
 */

export const BLOG_MINIMUM_POSTS = 2;
const RFC3339_TIMESTAMP_PATTERN = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(\.\d+)?(Z|[+-]\d{2}:\d{2})$/;

/** @type {readonly TestimonialRecord[]} */
export const approvedTestimonials = Object.freeze([]);

/** @type {readonly PackagingRecord[]} */
export const packagingItems = Object.freeze([]);

/**
 * Checks whether the post collection meets the publication threshold.
 *
 * @param {Array<any>} [posts=[]]
 * @returns {boolean}
 */
export const hasPublishableBlog = (posts = []) =>
  Array.isArray(posts) && posts.length >= BLOG_MINIMUM_POSTS;

const isLeapYear = (year) => year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);

const daysInMonth = (year, month) => {
  if (month === 2) return isLeapYear(year) ? 29 : 28;
  return [4, 6, 9, 11].includes(month) ? 30 : 31;
};

const isStrictRfc3339Timestamp = (value) => {
  const match = typeof value === 'string' ? value.match(RFC3339_TIMESTAMP_PATTERN) : null;
  if (!match) return false;

  const [, yearText, monthText, dayText, hourText, minuteText, secondText, , offset] = match;
  const year = Number(yearText);
  const month = Number(monthText);
  const day = Number(dayText);
  const hour = Number(hourText);
  const minute = Number(minuteText);
  const second = Number(secondText);
  const offsetMatch = offset === 'Z' ? null : offset.match(/^[+-](\d{2}):(\d{2})$/);
  const offsetHour = offsetMatch ? Number(offsetMatch[1]) : 0;
  const offsetMinute = offsetMatch ? Number(offsetMatch[2]) : 0;

  if (
    month < 1 || month > 12
    || day < 1 || day > daysInMonth(year, month)
    || hour > 23
    || minute > 59
    || second > 59
    || offset === '-00:00'
    || (offsetMatch && (offsetHour > 23 || offsetMinute > 59))
  ) {
    return false;
  }

  return !Number.isNaN(Date.parse(value));
};

export const normalizeBlogManifest = (manifest) => {
  const source = manifest && typeof manifest === 'object' && !Array.isArray(manifest)
    ? manifest
    : {};
  const withoutLegacyTimestamp = Object.fromEntries(
    Object.entries(source).filter(([key]) => key !== 'syncedAt'),
  );

  return {
    ...withoutLegacyTimestamp,
    sourceUpdatedAt: isStrictRfc3339Timestamp(source.sourceUpdatedAt)
      ? source.sourceUpdatedAt
      : null,
  };
};

export const blogManifest = normalizeBlogManifest(fallbackManifest || {
  blogsEnabled: false,
  minimumPosts: BLOG_MINIMUM_POSTS,
  totalPosts: 0,
  posts: [],
});

/** @type {readonly BlogPostSummary[]} */
export const blogPosts = Object.freeze(blogManifest.posts || []);

export const blogsEnabled = hasPublishableBlog(blogPosts);

/**
 * Returns all published blog post summaries.
 *
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {readonly BlogPostSummary[]}
 */
export const getPublishedBlogPosts = (posts = blogPosts) => posts;

/**
 * Returns a single post summary by slug.
 *
 * @param {string} slug
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {BlogPostSummary|undefined}
 */
export const getBlogPostSummary = (slug = '', posts = blogPosts) => {
  const normalized = slug.trim().toLowerCase();
  return posts.find((post) => post.slug.toLowerCase() === normalized);
};

/**
 * Returns the array of public paths for all published blog posts.
 * E.g. ['/blogs/coordinating-brand-market-commerce', ...]
 *
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {string[]}
 */
export const getPublishedBlogPaths = (posts = blogPosts) =>
  posts.map((post) => `/blogs/${post.slug}`);

/**
 * Checks if a given pathname corresponds to a published blog route.
 *
 * @param {string} pathname
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {boolean}
 */
export const isPublishedBlogRoute = (pathname = '', posts = blogPosts) => {
  const normalized = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname;
  if (normalized === '/blogs') return hasPublishableBlog(posts);
  return getPublishedBlogPaths(posts).includes(normalized);
};

// Vite lazy module map for full article bodies (prevents bundling all articles in main chunk)
const articleModules = import.meta.glob('../generated/blog/*.json');

/**
 * Loads the full article document (including Portable Text body) for a given slug.
 *
 * @param {string} slug
 * @returns {Promise<object|null>}
 */
export async function loadBlogPostContent(slug = '') {
  const normalized = slug.trim().toLowerCase();
  const moduleKey = `../generated/blog/${normalized}.json`;

  const loader = articleModules[moduleKey];
  if (typeof loader === 'function') {
    const mod = await loader();
    return mod.default || mod;
  }

  return null;
}
