/**
 * Publication Model & Article Data Layer for DSPL Insights.
 * Synchronously reads the deterministic snapshot generated by scripts/sync-blog-content.mjs
 * and provides lazy module loading for individual article bodies.
 */

import fallbackManifest from '../generated/blogManifest.json' with { type: 'json' };

/**
 * @typedef {Object} TestimonialRecord
 * @property {string} quote
 * @property {string} name
 * @property {string} role
 * @property {string} company
 * @property {string} consentReference
 */

/**
 * @typedef {Object} PackagingRecord
 * @property {string} image
 * @property {string} [backImage]
 * @property {string} sku
 * @property {string} collection
 * @property {string} description
 * @property {string} category
 * @property {string} alt
 */

/**
 * @typedef {Object} BlogPostSummary
 * @property {string} _id
 * @property {string} _createdAt
 * @property {string} _updatedAt
 * @property {string} slug
 * @property {string} title
 * @property {string} category
 * @property {string} publishedAt
 * @property {string} description
 * @property {{ minutes: number, text: string, wordCount: number }} readingTime
 * @property {Array<{ blockKey: string, id: string, text: string, level: number }>} headings
 * @property {object|null} [mainImage]
 * @property {object|null} [seo]
 */

export const BLOG_MINIMUM_POSTS = 2;

/** @type {readonly TestimonialRecord[]} */
export const approvedTestimonials = Object.freeze([]);

/** @type {readonly PackagingRecord[]} */
export const packagingItems = Object.freeze([]);

/**
 * Checks whether the post collection meets the publication threshold.
 *
 * @param {Array<any>} [posts=[]]
 * @returns {boolean}
 */
export const hasPublishableBlog = (posts = []) =>
  Array.isArray(posts) && posts.length >= BLOG_MINIMUM_POSTS;

export const blogManifest = fallbackManifest || {
  syncedAt: '',
  blogsEnabled: false,
  minimumPosts: BLOG_MINIMUM_POSTS,
  totalPosts: 0,
  posts: [],
};

/** @type {readonly BlogPostSummary[]} */
export const blogPosts = Object.freeze(blogManifest.posts || []);

export const blogsEnabled = hasPublishableBlog(blogPosts);

/**
 * Returns all published blog post summaries.
 *
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {readonly BlogPostSummary[]}
 */
export const getPublishedBlogPosts = (posts = blogPosts) => posts;

/**
 * Returns a single post summary by slug.
 *
 * @param {string} slug
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {BlogPostSummary|undefined}
 */
export const getBlogPostSummary = (slug = '', posts = blogPosts) => {
  const normalized = slug.trim().toLowerCase();
  return posts.find((post) => post.slug.toLowerCase() === normalized);
};

/**
 * Returns the array of public paths for all published blog posts.
 * E.g. ['/blogs/coordinating-brand-market-commerce', ...]
 *
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {string[]}
 */
export const getPublishedBlogPaths = (posts = blogPosts) =>
  posts.map((post) => `/blogs/${post.slug}`);

/**
 * Checks if a given pathname corresponds to a published blog route.
 *
 * @param {string} pathname
 * @param {readonly BlogPostSummary[]} [posts=blogPosts]
 * @returns {boolean}
 */
export const isPublishedBlogRoute = (pathname = '', posts = blogPosts) => {
  const normalized = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname;
  if (normalized === '/blogs') return hasPublishableBlog(posts);
  return getPublishedBlogPaths(posts).includes(normalized);
};

// Vite lazy module map for full article bodies (prevents bundling all articles in main chunk)
const articleModules = import.meta.glob('../generated/blog/*.json');

/**
 * Loads the full article document (including Portable Text body) for a given slug.
 *
 * @param {string} slug
 * @returns {Promise<object|null>}
 */
export async function loadBlogPostContent(slug = '') {
  const normalized = slug.trim().toLowerCase();
  const moduleKey = `../generated/blog/${normalized}.json`;

  const loader = articleModules[moduleKey];
  if (typeof loader === 'function') {
    const mod = await loader();
    return mod.default || mod;
  }

  return null;
}
